/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PendataanBuku;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author andika
 */
public class PendataanBuku extends javax.swing.JFrame {

    /**
     * Creates new form PendataanBuku
     */
    Connection con;
    Statement stm;
    ResultSet rs;
    private Object[][] tabelData;
    private String [] header={"kode", "judul", "pengarang", "penerbit", "isbn", "jenis", "tahunterbit", "kategori", "hargabeli", "stock"};
    
    public PendataanBuku() {
        initComponents();
        resetField();
        bacaData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtkode = new javax.swing.JTextField();
        txtjudul = new javax.swing.JTextField();
        txtpengarang = new javax.swing.JTextField();
        txtpenerbit = new javax.swing.JTextField();
        txtisbn = new javax.swing.JTextField();
        txttahunterbit = new javax.swing.JTextField();
        cbjenis = new javax.swing.JComboBox();
        cbkategori = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtstock = new javax.swing.JTextField();
        txthargabeli = new javax.swing.JTextField();
        jbhapus = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbkeluar = new javax.swing.JButton();
        jbbatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHasil = new javax.swing.JTable();
        jbtambah = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setText("PENDATAAN BUKU TOKO RYAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 588, -1));

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setText("KODE BUKU");

        jLabel3.setText("JUDUL BUKU");

        jLabel4.setText("PENGARANG");

        jLabel5.setText("PENERBIT");

        jLabel6.setText("ISBN");

        jLabel7.setText("JENIS");

        jLabel8.setText("TAHUN TERBIT");

        jLabel9.setText("KATEGORI");

        txtkode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeActionPerformed(evt);
            }
        });

        txtjudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjudulActionPerformed(evt);
            }
        });

        cbjenis.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "buku", "majalah", "koran", "novel" }));
        cbjenis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbjenisActionPerformed(evt);
            }
        });

        cbkategori.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "dewasa", "umum", "anak-anak", "remaja" }));
        cbkategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbkategoriActionPerformed(evt);
            }
        });

        jLabel10.setText("HARGA BELI");

        jLabel14.setText("STOCK");

        jbhapus.setText("HAPUS");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });

        jbsimpan.setText("SIMPAN");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });

        jbkeluar.setText("KELUAR");
        jbkeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkeluarActionPerformed(evt);
            }
        });

        jbbatal.setText("BATAL");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });

        tblHasil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblHasil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHasilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHasil);

        jbtambah.setText("TAMBAH");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cbkategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cbjenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txttahunterbit))
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel14))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jLabel5)
                                .addComponent(jLabel6))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtpengarang)
                                .addComponent(txtpenerbit)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(15, 15, 15)
                            .addComponent(jbtambah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(jbsimpan)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbhapus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbbatal)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jbkeluar))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(16, 16, 16))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtkode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtjudul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtpengarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtpenerbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtisbn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbjenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txttahunterbit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cbkategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txthargabeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtstock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jbhapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbsimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbbatal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbkeluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbtambah)))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbkeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkeluarActionPerformed
        int confirmasi = JOptionPane.showConfirmDialog(rootPane, "Tekan Yes Untuk Keluar?", "Confirm", JOptionPane.YES_NO_OPTION);
        if(confirmasi == JOptionPane.YES_OPTION){
            System.exit(0);
        }else{
        
        }
    }//GEN-LAST:event_jbkeluarActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        resetField();
        jbtambah.setEnabled(true);
    }//GEN-LAST:event_jbbatalActionPerformed

    private void cbjenisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbjenisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbjenisActionPerformed

    private void cbkategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbkategoriActionPerformed
        // TODO add your handling code here:
        // tombol simpan
    }//GEN-LAST:event_cbkategoriActionPerformed

    private void txtkodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeActionPerformed
        // TODO add your handling code here:
        //tombol ubah
    }//GEN-LAST:event_txtkodeActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // tombol tambah
        jbtambah.setEnabled(false);
        txtkode.setEnabled(true);
        txtjudul.setEnabled(true);
        txtpengarang.setEnabled(true);
        txtpenerbit.setEnabled(true);
        txtisbn.setEnabled(true);
        cbjenis.setEnabled(true);
        txttahunterbit.setEnabled(true);
        cbkategori.setEnabled(true); // iki kategori
        txthargabeli.setEnabled(true);
        txtstock.setEnabled(true);
        jbsimpan.setEnabled(true);
        jbhapus.setEnabled(false);
        jbbatal.setEnabled(true);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void txtjudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjudulActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        //get kode dari txtfieldkode
        //hapus dr database where kode =                 
        int konfirmasiHapus = JOptionPane.showConfirmDialog(rootPane, "Data akan dihapus?", "Peringatan!", JOptionPane.YES_NO_OPTION);
        
        if(konfirmasiHapus == JOptionPane.YES_OPTION){
            String kode = txtkode.getText();
            openDB();
            try {
                stm = con.createStatement();
                stm.executeUpdate("delete from buku where kode = '"+kode+"'");
                JOptionPane.showMessageDialog(rootPane, "Buku dengan kode : "+kode+" Telah dihapus!", "Infromation", JOptionPane.INFORMATION_MESSAGE);
                bacaData();
                resetField();
            } catch (SQLException ex) {
                Logger.getLogger(PendataanBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
        
        }
    }//GEN-LAST:event_jbhapusActionPerformed

    private void tblHasilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHasilMouseClicked
        setField();
    }//GEN-LAST:event_tblHasilMouseClicked

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        String kode, judul, pengarang, penerbit, isbn, jenis, tahunterbit, kategori, hargabeli, stock;
        kode = txtkode.getText();
        judul = txtjudul.getText();
        pengarang = txtpengarang.getText();
        penerbit = txtpenerbit.getText();
        isbn = txtisbn.getText();
        tahunterbit = txttahunterbit.getText();
        hargabeli = txthargabeli.getText();
        stock = txtstock.getText();
        //combo box
        kategori = String.valueOf(cbkategori.getSelectedItem());
        jenis = String.valueOf(cbjenis.getSelectedItem());
        /*if(("".equals(kode)) && ("".equals(judul))){
            JOptionPane.showMessageDialog(rootPane, "Judul dan Pengarang ksoong");
        }*/
        if(("".equals(kode))){
        //cek masih kosong maka keluarkan pesan error, kosongkan field
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan kode buku", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(judul)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan Judul Buku", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(pengarang)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan Pengarang Buku ","Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(penerbit)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan Penerbit Buku", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(isbn)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan ISBN Buku", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(tahunterbit)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan Tahun terbit Buku Kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(hargabeli)){
            JOptionPane.showMessageDialog(rootPane, "Anda belum menginputkan harga beli Buku", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else if("".equals(stock)){
            JOptionPane.showMessageDialog(rootPane, " Stock Kosong", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
        else{
            //
            openDB();
            try {
                stm = con.createStatement();
                rs = stm.executeQuery("select * from buku where kode='"+kode+"'");
                if(rs.next()){
                    JOptionPane.showMessageDialog(rootPane, "Data Buku Sudah Ada!");
                }else{
                    stm = con.createStatement();
                    stm.executeUpdate("insert into buku set kode='"+kode+"', judul='"+judul+"', pengarang='"+pengarang+"', penerbit='"+penerbit+"', isbn='"+isbn+"', jenis='"+jenis+"', tahunterbit='"+tahunterbit+"', kategori='"+kategori+"', hargabeli='"+hargabeli+"', stock='"+stock+"'");
                    JOptionPane.showMessageDialog(rootPane, "Data berhasil tersimpan!"); //simpan ke DB
                    bacaData();
                }
            } catch (SQLException ex) {
                Logger.getLogger(PendataanBuku.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        
    }//GEN-LAST:event_jbsimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendataanBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new PendataanBuku().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbjenis;
    private javax.swing.JComboBox cbkategori;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbbatal;
    private javax.swing.JButton jbhapus;
    private javax.swing.JButton jbkeluar;
    private javax.swing.JButton jbsimpan;
    private javax.swing.JButton jbtambah;
    private javax.swing.JTable tblHasil;
    private javax.swing.JTextField txthargabeli;
    private javax.swing.JTextField txtisbn;
    private javax.swing.JTextField txtjudul;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtpenerbit;
    private javax.swing.JTextField txtpengarang;
    private javax.swing.JTextField txtstock;
    private javax.swing.JTextField txttahunterbit;
    // End of variables declaration//GEN-END:variables

 

    private void setField() {
        //memasang data klik pada field
        //membuka tombol ubah, hapus, batal
        int row = tblHasil.getSelectedRow();
        
        txtkode.setText((String)tblHasil.getValueAt(row, 0));
        txtjudul.setText((String)tblHasil.getValueAt(row, 1));
        txtpengarang.setText((String)tblHasil.getValueAt(row, 2));
        txtpenerbit.setText((String)tblHasil.getValueAt(row, 3));
        txtisbn.setText((String)tblHasil.getValueAt(row, 4));
        cbjenis.setSelectedItem((String)tblHasil.getValueAt(row, 5));        
        txttahunterbit.setText((String)tblHasil.getValueAt(row, 6));
        cbkategori.setSelectedItem((String)tblHasil.getValueAt(row, 7));
        txthargabeli.setText((String)tblHasil.getValueAt(row, 8));
        txtstock.setText((String)tblHasil.getValueAt(row, 9));
        //combo box       
                
//        jbubah.setEnabled(true);
        jbbatal.setEnabled(true);
        jbhapus.setEnabled(true);
    }

    private void resetField() {
        txtkode.setText(null);
        txtkode.setEnabled(false);
        txtjudul.setText(null);
        txtjudul.setEnabled(false);
        txtpengarang.setText(null);
        txtpengarang.setEnabled(false);
        txtpenerbit.setText(null);
        txtpenerbit.setEnabled(false);
        txtisbn.setText(null);
        txtisbn.setEnabled(false);
        cbjenis.setSelectedIndex(0);
        cbjenis.setEnabled(false);
        txttahunterbit.setText(null);
        txttahunterbit.setEnabled(false);
        cbkategori.setSelectedIndex(0);
        cbkategori.setEnabled(false);
        txthargabeli.setText(null);
        txthargabeli.setEnabled(false);
        txtstock.setText(null);
        txtstock.setEnabled(false);
//        jbubah.setEnabled(false);
        jbsimpan.setEnabled(false);
        jbhapus.setEnabled(false);
        jbbatal.setEnabled(false);
    }

    private void bacaData() {
        openDB();
        try {
            stm = con.createStatement();
            rs=stm.executeQuery("Select * FROM buku");
            java.sql.ResultSetMetaData meta=rs.getMetaData();
            int col=meta.getColumnCount();
            int baris=0;
            String jbt;
            while(rs.next()){
                baris=rs.getRow();
            }
            
            tabelData=new Object[baris][col];
            int x=0;
            String kb=null;
            rs.beforeFirst();
            while(rs.next()){
                tabelData[x][0]=rs.getString("kode"); 
                tabelData[x][1]=rs.getString("judul");
                tabelData[x][2]=rs.getString("pengarang");
                tabelData[x][3]=rs.getString("penerbit");
                tabelData[x][4]=rs.getString("isbn");
                tabelData[x][5]=rs.getString("jenis");
                tabelData[x][6]=rs.getString("tahunterbit");
                tabelData[x][7]=rs.getString("kategori");
                tabelData[x][8]=rs.getString("hargabeli");
                tabelData[x][9]=rs.getString("stock");
                x++;
            }
            
            tblHasil.setModel(new DefaultTableModel(tabelData,header));
            
        } catch (SQLException ex) {
            Logger.getLogger(PendataanBuku.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void openDB() {
       Koneksi k = new Koneksi();
       con = k.DatabaseToko();
    }
}
